#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="admin")]
public partial class carDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertcar(car instance);
  partial void Updatecar(car instance);
  partial void Deletecar(car instance);
  #endregion
	
	public carDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["adminConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public carDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public carDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public carDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public carDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<car> cars
	{
		get
		{
			return this.GetTable<car>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.car")]
public partial class car : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _shop_no;
	
	private string _car_photo;
	
	private string _address;
	
	private string _mobile_no;
	
	private string _status;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void Onshop_noChanging(string value);
    partial void Onshop_noChanged();
    partial void Oncar_photoChanging(string value);
    partial void Oncar_photoChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void Onmobile_noChanging(string value);
    partial void Onmobile_noChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
	
	public car()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shop_no", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string shop_no
	{
		get
		{
			return this._shop_no;
		}
		set
		{
			if ((this._shop_no != value))
			{
				this.Onshop_noChanging(value);
				this.SendPropertyChanging();
				this._shop_no = value;
				this.SendPropertyChanged("shop_no");
				this.Onshop_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_photo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string car_photo
	{
		get
		{
			return this._car_photo;
		}
		set
		{
			if ((this._car_photo != value))
			{
				this.Oncar_photoChanging(value);
				this.SendPropertyChanging();
				this._car_photo = value;
				this.SendPropertyChanged("car_photo");
				this.Oncar_photoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string address
	{
		get
		{
			return this._address;
		}
		set
		{
			if ((this._address != value))
			{
				this.OnaddressChanging(value);
				this.SendPropertyChanging();
				this._address = value;
				this.SendPropertyChanged("address");
				this.OnaddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile_no", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string mobile_no
	{
		get
		{
			return this._mobile_no;
		}
		set
		{
			if ((this._mobile_no != value))
			{
				this.Onmobile_noChanging(value);
				this.SendPropertyChanging();
				this._mobile_no = value;
				this.SendPropertyChanged("mobile_no");
				this.Onmobile_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
